# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtnorm_cpp <- function(n, mean, sd, lower, upper) {
    .Call('_SFAsim_rtnorm_cpp', PACKAGE = 'SFAsim', n, mean, sd, lower, upper)
}

